version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands: 
      - aws s3 cp --recursive ./buil s3://rams-awspipelinedemo/
      - aws cloudfront create-invalidation --distribution-id E19A9EEODLS8XH --path /\*
